[pytest]
markers =
    smoke: Тесты для проверки базовой функциональности
    regression: Тесты для проверки полного функционала
    ui: Тесты пользовательского интерфейса

addopts = --alluredir=reports/allure_report
